# dependencies
dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.4.1
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.1'

# networks
networks:
  development:
    verify: False
  rinkeby:
    verify: False
    

# wallets
dotenv:
  .env
wallets:
  from_key: ${PRIVATE_KEY_CHROME_MM}
infura:
  infura_key: ${WEB3_INFURA_PROJECT_ID}
  